"""empty message

Revision ID: 484427a88da3
Revises: ae1dc3f9a099
Create Date: 2021-07-28 17:11:28.511709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484427a88da3'
down_revision = 'ae1dc3f9a099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarioscargasembarcadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=300), nullable=True),
    sa.Column('carga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['cargasembarcadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarioscargasembarcadores_timestamp'), 'comentarioscargasembarcadores', ['timestamp'], unique=False)
    op.create_table('comentariosfletestransportistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=300), nullable=True),
    sa.Column('flete_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flete_id'], ['fletestransportistas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentariosfletestransportistas_timestamp'), 'comentariosfletestransportistas', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comentariosfletestransportistas_timestamp'), table_name='comentariosfletestransportistas')
    op.drop_table('comentariosfletestransportistas')
    op.drop_index(op.f('ix_comentarioscargasembarcadores_timestamp'), table_name='comentarioscargasembarcadores')
    op.drop_table('comentarioscargasembarcadores')
    # ### end Alembic commands ###
