"""empty message

Revision ID: 9549901946dc
Revises: 1179ad96b1c4
Create Date: 2021-08-03 09:05:18.551195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9549901946dc'
down_revision = '1179ad96b1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rol', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rol')
    # ### end Alembic commands ###
