"""empty message

Revision ID: c010cd015708
Revises: fc4b2f4a95a6
Create Date: 2021-07-21 18:27:37.534177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c010cd015708'
down_revision = 'fc4b2f4a95a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fletestransportistas', 'helper')
    # ### end Alembic commands ###
