"""empty message

Revision ID: c469ffcfd82e
Revises: 9549901946dc
Create Date: 2021-08-03 18:28:37.507617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c469ffcfd82e'
down_revision = '9549901946dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacto', sa.Column('contacto', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacto', 'contacto')
    # ### end Alembic commands ###
